services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: unidam
      POSTGRES_USER: unidam_user
      POSTGRES_PASSWORD: unidam_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=unidam_user
      - POSTGRES_PASSWORD=unidam_password
      - POSTGRES_DB=unidam
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: